name: Build and Push {{ cookiecutter.project_name }} Image

on:
  push:
    branches:
      - main
  
env:
    CONTAINER_REGISTRY_SERVER: genoaperformance.azurecr.io
    CONTAINER_IMAGE: {{ cookiecutter.project_slug }}

jobs:
    build-push:
        env:
          USER: {% raw %}${{ secrets.PRIVATE_REPO_USER }}{% endraw %}
          TOKEN: {% raw %}${{ secrets.PRIVATE_REPO_SECRET }}{% endraw %}

        permissions:
          contents: read
          id-token: write

        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Get last git commit hash
          id: vars
          run: echo "::set-output name=last_commit_hash::$(git rev-parse --short HEAD)"

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to Genoa Performance private registry
          uses: docker/login-action@v2
          with:
            registry: {% raw %}${{ env.CONTAINER_REGISTRY_SERVER}}{% endraw %}
            username: {% raw %}${{ secrets.CONTAINER_REGISTRY_USERNAME }}{% endraw %}
            password: {% raw %}${{ secrets.CONTAINER_REGISTRY_PASSWORD }}{% endraw %}

        - name: Build and push container image
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: |
                {% raw %}${{ env.CONTAINER_REGISTRY_SERVER }}{% endraw %}/{% raw %}${{ env.CONTAINER_IMAGE }}{% endraw %}:{% raw %}${{ steps.vars.outputs.last_commit_hash }}{% endraw %}
                {% raw %}${{ env.CONTAINER_REGISTRY_SERVER }}{% endraw %}/{% raw %}${{ env.CONTAINER_IMAGE }}{% endraw %}:latest
            file: ./Dockerfile