name: Build and Push {{ cookiecutter.project_name }} Image

on:
  push:
    branches:
      - main
  
env:
    CONTAINER_REGISTRY_SERVER: genoaperformance.azurecr.io
    CONTAINER_IMAGE: {{ cookiecutter.project_slug }}

jobs:
    build-push:
        env:
          USER: ${{ secrets.PRIVATE_REPO_USER }}
          TOKEN: ${{ secrets.PRIVATE_REPO_SECRET }}

        permissions:
          contents: read
          id-token: write

        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Get last git commit hash
          id: vars
          run: echo "::set-output name=last_commit_hash::$(git rev-parse --short HEAD)"

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Log in to Genoa Performance private registry
          uses: docker/login-action@v2
          with:
            registry: ${{ env.CONTAINER_REGISTRY_SERVER}}
            username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
            password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

        - name: Build and push container image
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: |
                ${{ env.CONTAINER_REGISTRY_SERVER }}/${{ env.CONTAINER_IMAGE }}:${{ steps.vars.outputs.last_commit_hash }}
                ${{ env.CONTAINER_REGISTRY_SERVER }}/${{ env.CONTAINER_IMAGE }}:latest
            file: ./Dockerfile