name: '{{ cookiecutter.project_slug }}'
version: '1.0.0'

profile: '{{ cookiecutter.project_slug }}'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: [models, docs]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +persist_docs:
    relation: true
    columns: true
  {{ cookiecutter.project_slug }}:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
      #+schema: xyz

  post-hook:
    - "{% raw %}{{ create_latest_version_view() }}{% endraw %}"
